-- MySQL Script generated by MySQL Workbench
-- Mon Feb 17 22:25:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema sch_invest
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sch_invest` ;

-- -----------------------------------------------------
-- Schema sch_invest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sch_invest` ;
USE `sch_invest` ;

-- -----------------------------------------------------
-- Table `instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituicao` ;

CREATE TABLE IF NOT EXISTS `instituicao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `img_logo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo` ;

CREATE TABLE IF NOT EXISTS `grupo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta` ;

CREATE TABLE IF NOT EXISTS `conta` (
  `id` INT NOT NULL,
  `agencia` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `saldo` DECIMAL(7,2) NULL,
  `fgc_conta` TINYINT NULL,
  `conta_ativa` TINYINT NULL,
  `instituicao_ìd` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conta_instituicao1_idx` (`instituicao_ìd` ASC) VISIBLE,
  INDEX `fk_conta_grupo1_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_conta_instituicao1`
    FOREIGN KEY (`instituicao_ìd`)
    REFERENCES `instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `investimento` ;

CREATE TABLE IF NOT EXISTS `investimento` (
  `id` INT NOT NULL,
  `nome_ativo` VARCHAR(45) NULL,
  `quantidade_comprada` DECIMAL(4,2) NULL,
  `valor_aporte` DECIMAL(7,2) NULL,
  `rentabilidade_contratada` VARCHAR(45) NULL,
  `data_aporte` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `liquidez` VARCHAR(45) NULL,
  `indexador` VARCHAR(45) NULL,
  `data_vencimento` VARCHAR(45) NULL,
  `fgc_investimento` TINYINT NULL,
  `conta_id` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_investimento_conta1_idx` (`conta_id` ASC) VISIBLE,
  INDEX `fk_investimento_grupo1_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_investimento_conta1`
    FOREIGN KEY (`conta_id`)
    REFERENCES `conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investimento_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vencimento_detalhe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vencimento_detalhe` ;

CREATE TABLE IF NOT EXISTS `vencimento_detalhe` (
  `id` INT NOT NULL,
  `valo_recebido` DECIMAL(7,2) NULL,
  `percentual_ganho` DECIMAL(5,2) NULL,
  `investimento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vencimento_detalhe_investimento1_idx` (`investimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_vencimento_detalhe_investimento1`
    FOREIGN KEY (`investimento_id`)
    REFERENCES `investimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meta` ;

CREATE TABLE IF NOT EXISTS `meta` (
  `id` INT NOT NULL,
  `valor_alvo` DECIMAL(7,2) NULL,
  `data_estimada` VARCHAR(45) NULL,
  `descricao_detalhada` VARCHAR(200) NULL,
  `status_meta` VARCHAR(45) NULL,
  `investimento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_meta_investimento1_idx` (`investimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_meta_investimento1`
    FOREIGN KEY (`investimento_id`)
    REFERENCES `investimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lista` ;

CREATE TABLE IF NOT EXISTS `lista` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

CREATE TABLE IF NOT EXISTS `item` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `lista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_lista1_idx` (`lista_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_lista1`
    FOREIGN KEY (`lista_id`)
    REFERENCES `lista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `armazenamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armazenamento` ;

CREATE TABLE IF NOT EXISTS `armazenamento` (
  `id` INT NOT NULL,
  `local_interno` VARCHAR(100) NULL,
  `local_externo` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `especie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `especie` ;

CREATE TABLE IF NOT EXISTS `especie` (
  `id` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `armazenamento_id` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_especie_armazenamento1_idx` (`armazenamento_id` ASC) VISIBLE,
  INDEX `fk_especie_grupo1_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_especie_armazenamento1`
    FOREIGN KEY (`armazenamento_id`)
    REFERENCES `armazenamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especie_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cartao` ;

CREATE TABLE IF NOT EXISTS `cartao` (
  `id` INT NOT NULL,
  `modalidade` VARCHAR(45) NULL,
  `saldo_debito` DECIMAL(7,2) NULL,
  `limite_credito` DECIMAL(7,2) NULL,
  `img_bandeira` VARCHAR(45) NULL,
  `conta_id` INT NOT NULL,
  `armazenamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cartao_armazenamento1_idx` (`armazenamento_id` ASC) VISIBLE,
  INDEX `fk_cartao_conta1_idx` (`conta_id` ASC) VISIBLE,
  CONSTRAINT `fk_cartao_armazenamento1`
    FOREIGN KEY (`armazenamento_id`)
    REFERENCES `armazenamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartao_conta1`
    FOREIGN KEY (`conta_id`)
    REFERENCES `conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
